### PR TITLE
Added GetAuth

### PR DESCRIPTION
**Pull request by domaspoliakas**
[ch13272]

### CODE REVIEW

**Comment by rintcius** [comment]
@domaspoliakas The implementation is meant to be added here, I guess?

**Comment by domaspoliakas** [comment]
No. My intention was to add the param everywhere and get everything merged, then as a separate step implement the sso stuff and merge it separately.

**Review by rintcius — APPROVED** [review]
Ah ok. Personally, I would fully implement a feature before starting to merge (in order to reduce chances of having to propagate breaking changes multiple times). 

I guess this interface change is simple enough though, so there's not that much risk. Feel free to do the impl separately.

**Comment by domaspoliakas** [comment]
I think on reexamination - you're definitely right, there's no reason to cause 2 propagations. When I scoped this out it did not occur to me that this would be something I should consider, but it does very much make sense now.

I'll just get it implemented here and merge it all in one swoop as you suggested.

**Comment by domaspoliakas** [comment]
This is superseded by #286

**Pull request closed without merging**
